#! /bin/sh

# Startup applications/commands
pgrep -x sxhkd > /dev/null || sxhkd & 
picom & 
nitrogen --restore & 
/home/jonathan/.config/polybar/launch.sh --blocks &
polybar-msg cmd restart &
gammy &
xsetroot -cursor_name left_ptr &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Gaps
bspc config border_width        0
bspc config focused_border_color \#6da4cd
bspc config normal_border_color \#3b4244
bspc config window_gap          9

# Application rules
bspc rule -a discord desktop=5 state=tiled
bspc rule -a Google-chrome desktop=2 state=tiled
bspc rule -a gammy desktop=1 state=floating
bspc rule -a kitty state=floating rectangle=270x250
bspc rule -a Org.gnome.Nautilus state=floating rectangle=500x450

# Window rules
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        10

# Preselection rules
bspc config presel_feedback_color \#6da4cd